# Generated by Django 6.0.6 on 2026-06-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conductores',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='estaciones',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estacion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estaciones',
            },
        ),
        migrations.CreateModel(
            name='pasajeros',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pasajeros',
            },
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='rutas',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=100)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('distancia_km', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_destino', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, related_name='destino_estacion', to='gestion_transporte.estaciones')),
                ('id_origen', models.ForeignKey(db_column='id_origen', on_delete=django.db.models.deletion.CASCADE, related_name='origen_estacion', to='gestion_transporte.estaciones')),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.CreateModel(
            name='mantenimientos',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_mantenimiento', models.DateTimeField()),
                ('costo', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.vehiculos')),
            ],
            options={
                'db_table': 'mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_conductor', models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.conductores')),
                ('id_ruta', models.ForeignKey(db_column='id_ruta', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.rutas')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.vehiculos')),
            ],
            options={
                'db_table': 'viajes',
            },
        ),
        migrations.CreateModel(
            name='boletos',
            fields=[
                ('id_boleto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_pasajero', models.ForeignKey(db_column='id_pasajero', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.pasajeros')),
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.viajes')),
            ],
            options={
                'db_table': 'boletos',
            },
        ),
        migrations.AddConstraint(
            model_name='rutas',
            constraint=models.CheckConstraint(condition=models.Q(('id_origen', models.F('id_destino')), _negated=True), name='origen_destino_diferentes'),
        ),
    ]
