# Generated by Django 6.0.6 on 2026-06-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='conductores',
            name='licencia',
        ),
        migrations.AlterField(
            model_name='conductores',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estaciones',
            name='nombre_estacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='nombre_ruta',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='placa',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_conductor', models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.conductores')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='licencia',
            fields=[
                ('id_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_conductor', models.ForeignKey(db_column='id_conductor', on_delete=django.db.models.deletion.CASCADE, to='gestion_transporte.conductores')),
            ],
            options={
                'db_table': 'licencia',
            },
        ),
    ]
