# Generated by Django 6.0.6 on 2026-06-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transporte', '0002_remove_conductores_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductores',
            name='documento',
        ),
    ]
