# Generated by Django 6.0.6 on 2026-06-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_transporte', '0003_remove_conductores_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='rutas',
            name='hora_salida',
        ),
    ]
